version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["uvicorn", "aperture.main:app", "--reload", "--host", "0.0.0.0"]

    env_file:
      - .env

    environment:
      - BASE_URL=${BASE_URL:-http://localhost:8000/}
      - USE_DEV_KEYS=true

    volumes:
      - .:/app:rw

    ports:
      - "8000:8000"
